# Generated by Django 4.1.6 on 2023-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('subtitle', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
