# Generated by Django 4.1.6 on 2023-02-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
