# Generated by Django 4.1.6 on 2023-02-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_author_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.author')),
            ],
        ),
    ]
