# Generated by Django 4.1.6 on 2023-02-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_article_likes_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='../default.jpg', upload_to='article_photos'),
        ),
    ]
