# Generated by Django 4.1.6 on 2023-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_article_img_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='files/article_photos'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(upload_to='files/author_photos'),
        ),
    ]
